repository: LaBiOS/bioportainer
theme: jekyll-theme-minimal
name: BioPortainer
title: BioPortainer
description: a Docker UI for Bioinformatics
author: Menegidio, F.B.
author_email: fabiano.menegidio@biology.bio.br

logo: https://github.com/LaBiOS/BioPortainer/blob/master/images/logo.png
show_downloads: true
