repository: LaBiOS/bioportainer
theme: jekyll-theme-slate
name: BioPortainer
title: BioPortainer
description: a Docker UI for Bioinformatics
author: Menegidio, F.B.
author_email: fabiano.menegidio@biology.bio.br

show_downloads: true
