version: '2'

services:
  portainer:
    image: labios/bioportainer
    ports:
      - "9000:9000"
    command: --templates https://labios.github.io/BioPortainer/templates.json
    networks:
      - bioportainer-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/bioportainer_data:/data

networks:
  bioportainer-net:
