version: '2'

services:
  portainer:
    image: labios/bioportainer
    ports:
      - "9000:9000"
    command: --templates http://bioportainer.ml/templates.json
    networks:
      - bioportainer-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./bioportainer_data:/data

networks:
  bioportainer-net:
